language: php

sudo: false

matrix:
  include:
    - env: DBTYPE=mysql; MW=1.28.2
      php: 5.6
    - env: DBTYPE=mysql; MW=1.27.3
      php: 5.5
    - env: DBTYPE=mysql; MW=master; SMW=2.4.6
      php: 7.1
    - env: DBTYPE=sqlite; MW=1.27.0; SMW=2.4.1
      php: 5.5
    - env: DBTYPE=sqlite; MW=master; TYPE=coverage
      php: 5.6

install:
  - travis_retry composer self-update
  - bash .travis.install.sh

script: ../phase3/tests/phpunit/phpunit.php -c ../phase3/extensions/Maps/phpunit.xml.dist

after_success:
  - if [[ "$TYPE" != "coverage" ]]; then exit 0; fi
  - ../phase3/tests/phpunit/phpunit.php -c ../phase3/extensions/Maps/phpunit.xml.dist --coverage-clover coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

cache:
  directories:
    - $HOME/.composer/cache
