language: php

env:
  - THENEEDFORTHIS=FAIL

matrix:
  include:
    - env: DBTYPE=mysql; MW=master
      php: 5.6
    - env: DBTYPE=mysql; MW=1.22.0
      php: 5.3
    - env: DBTYPE=mysql; MW=1.23.0
      php: 5.4
    - env: DBTYPE=sqlite; MW=master; TYPE=coverage
      php: 5.5
    - env: DBTYPE=sqlite; MW=1.24.0
      php: 5.3
  exclude:
    - env: THENEEDFORTHIS=FAIL
  allow_failures:
    - env: DBTYPE=sqlite; MW=1.25.0

before_script: bash ./build/travis/before_script.sh

script: bash ./build/travis/script.sh

after_success: bash ./build/travis/after_success.sh
